@extends('errors.layout')
@section('code', '429')
@section('icon', 'ti-hourglass')
@section('heading', 'Too many requests')
@section('message', 'Please wait a moment before trying again. This limit protects account access and system stability.')
